apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-sta-origination-api
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/origination-api
    digest: sha256:94ea8d38c46341db044ede4ef6586e7cef96a2745d28fef2f114b5dd3d35880a
replicas:
  - name: origination-api
    count: 1
labels:
  - pairs:
      lendora.io/environment: sta
