apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-dev-1
resources:
- ../../base
images:
- name: ghcr.io/spark-harness/origination-api
  digest: sha256:183f229a4a8f05cbb430f219e8b9d149a79dcbaf9c85d7fbb1c1c278c88f578e
replicas:
- name: origination-api
  count: 1
labels:
- pairs:
    lendora.io/environment: dev-1
patches:
- target:
    kind: ConfigMap
    name: origination-api-config
  patch: "- op: replace\n  path: /data/SPRING_PROFILES_ACTIVE\n  value: dev-1\n- op:\
    \ replace\n  path: /data/ORIGINATION_JDBC_URL\n  value: jdbc:postgresql://postgres.lendora-shared-postgres.svc.cluster.local:5432/dev_1_origination\n\
    - op: replace\n  path: /data/ORIGINATION_JDBC_USERNAME\n  value: dev_1_origination\n\
    - op: replace\n  path: /data/ORIGINATION_QUOTE_API_BASE_URL\n  value: http://quote-api.lendora-dev-1.svc.cluster.local\n\
    - op: replace\n  path: /data/SPARK_ORIGINATION_CONSUL_URL\n  value: http://consul.lendora-shared-consul.svc.cluster.local:8500\n\
    - op: replace\n  path: /data/SPARK_ORIGINATION_CONSUL_SERVICE_NAME\n  value: dev-1-origination-api\n\
    - op: replace\n  path: /data/SPARK_ORIGINATION_CONSUL_SERVICE_ADDRESS\n  value:\
    \ origination-api.lendora-dev-1.svc.cluster.local\n- op: replace\n  path: /data/SPARK_ORIGINATION_CONSUL_HEALTH_CHECK_URL\n\
    \  value: http://origination-api.lendora-dev-1.svc.cluster.local:80/ready"
- target:
    kind: ConfigMap
    name: origination-api-consul-config
  patch: "- op: replace\n  path: /data/origination-api.yml\n  value: |\n    spark:\n\
    \      origination:\n        quote-api-base-url: http://quote-api.lendora-dev-1.svc.cluster.local\n\
    \        quote-api-timeout: 3s\n        consul:\n          enabled: true\n   \
    \       service-name: dev-1-origination-api\n          service-address: origination-api.lendora-dev-1.svc.cluster.local\n\
    \          http-port: 80\n          health-check-url: http://origination-api.lendora-dev-1.svc.cluster.local:80/ready\n\
    \    otel:\n      service:\n        name: origination-api\n      traces:\n   \
    \     exporter: otlp\n        sampler: parentbased_traceidratio\n        sampler.arg:\
    \ 0.1\n      exporter:\n        otlp:\n          traces:\n            protocol:\
    \ http/protobuf"
- target:
    kind: Job
    name: origination-api-consul-config
  patch: "- op: replace\n  path: /spec/template/spec/containers/0/command/2\n  value:\
    \ |\n    curl --fail --request PUT --data-binary @/config/origination-api.yml\
    \ \\\n      http://consul.lendora-shared-consul.svc.cluster.local:8500/v1/kv/spark/lendora/dev-1/origination-api/config"
- target:
    kind: NetworkPolicy
    name: origination-api-ingress
  patch: "- op: replace\n  path: /spec/ingress\n  value:\n    - from:\n        - namespaceSelector:\n\
    \            matchLabels:\n              kubernetes.io/metadata.name: lendora-dev-1\n\
    \      ports:\n        - protocol: TCP\n          port: 8080\n        - protocol:\
    \ TCP\n          port: 80\n    - from:\n        - namespaceSelector:\n       \
    \     matchLabels:\n              kubernetes.io/metadata.name: lendora-shared-consul\n\
    \      ports:\n        - protocol: TCP\n          port: 8080"
