apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-dev-1
resources:
- ../../base
- runtime-config-consul.yaml
images:
- name: ghcr.io/spark-harness/fides
  digest: sha256:dbfc66fef1f442a48d395a0b0334675774fe6d437822eb4c00d72e002526f7fa
replicas:
- name: fides
  count: 1
labels:
- pairs:
    lendora.io/environment: dev-1
patches:
- target:
    kind: Deployment
    name: fides
  patch: "- op: replace\n  path: /spec/template/spec/containers/0/env/0/value\n  value:\
    \ dev-1\n- op: replace\n  path: /spec/template/spec/containers/0/env/1/value\n\
    \  value: http://consul.lendora-shared-consul.svc.cluster.local:8500\n- op: replace\n\
    \  path: /spec/template/spec/containers/0/env/2/value\n  value: spark/lendora/dev-1/fides-web/runtime-config\n\
    - op: replace\n  path: /spec/template/spec/containers/0/env/4/value\n  value:\
    \ https://dev-1-api.fuzzytails.fun/api/v1"
