apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: business-image-release
  namespace: argo-events
spec:
  template:
    serviceAccountName: github-sensor
  dependencies:
    - name: business-repo-master-push
      eventSourceName: github
      eventName: business-repo
      filters:
        data:
          - path: headers.X-Github-Event
            type: string
            value:
              - push
          - path: body.ref
            type: string
            value:
              - refs/heads/master
  triggers:
    - template:
        name: business-repo-image-release
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: business-repo-image-release-
                namespace: argo
              spec:
                workflowTemplateRef:
                  name: github-image-release
                arguments:
                  parameters:
                    - name: repo-owner
                      value: spark-harness
                    - name: repo-name
                      value: business-repo
                    - name: commit-sha
                    - name: source-ref
                      value: master
                    - name: gitops-repo
                      value: spark-harness/gitops-repo
                    - name: gitops-branch
                      value: master
                    - name: status-context
                      value: spark/business-image-release
          parameters:
            - src:
                dependencyName: business-repo-master-push
                dataKey: body.after
              dest: spec.arguments.parameters.2.value
