apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-sensor
  namespace: argo-events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-sensor
  namespace: argo
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-sensor
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: github-sensor
    namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-sensor
