apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github-sensor-rbac.yaml
  - github-webhook-eventsource.yaml
  - github-pr-smoke-sensor.yaml
  - github-repo-gates-sensor.yaml
  - business-image-release-sensor.yaml
