apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-workflows/releases/download/v4.0.6/install.yaml
  - https://github.com/argoproj/argo-events/releases/download/v1.9.10/install.yaml
  - spark-ci-runner-rbac.yaml
  - eventbus.yaml
