apiVersion: v1
kind: Namespace
metadata:
  name: argo
  labels:
    app.kubernetes.io/part-of: spark-ci
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
  labels:
    app.kubernetes.io/part-of: spark-ci
