apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-sta-fides
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/fides
    digest: sha256:60ff63c63633c385ad7cc1bb56e793de775f53e9c7ccaa61adf1c9e70fd27af2
replicas:
  - name: fides
    count: 1
labels:
  - pairs:
      lendora.io/environment: sta
