apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-sta-fides
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/fides
    digest: sha256:57fbc974ac53d24b81511b781b21f73ce69dc4cb415a81e1e2491c934e1df599
replicas:
  - name: fides
    count: 1
labels:
  - pairs:
      lendora.io/environment: sta
