apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-sta-fides
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/fides
    digest: sha256:37212ca4e5a028dbc41c707aa214f2fd8955f77ecf0e8de98cc98a2e2fb98c8f
replicas:
  - name: fides
    count: 1
labels:
  - pairs:
      lendora.io/environment: sta
