apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spark-prod
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/applicant-api
    newTag: prod-placeholder
replicas:
  - name: applicant-api
    count: 2
labels:
  - pairs:
      spark.io/environment: prod
