apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - namespaces/spark.yaml
  - argocd-project.yaml
  - argocd-apps/platform-argocd.yaml
  - argocd-apps/applicant-api.yaml
