apiVersion: v1
kind: ConfigMap
metadata:
  name: origination-api-config
  labels:
    app.kubernetes.io/name: origination-api
    app.kubernetes.io/part-of: lendora
data:
  SPRING_PROFILES_ACTIVE: sta-1
  SERVER_PORT: "8080"
  ORIGINATION_JDBC_URL: jdbc:postgresql://postgres.lendora-shared-postgres.svc.cluster.local:5432/sta_1_origination
  ORIGINATION_JDBC_USERNAME: sta_1_origination
  ORIGINATION_QUOTE_API_BASE_URL: http://quote-api.lendora-sta-1.svc.cluster.local
  ORIGINATION_QUOTE_API_TIMEOUT: 3s
  SPARK_ORIGINATION_CONSUL_ENABLED: "true"
  SPARK_ORIGINATION_CONSUL_URL: http://consul.lendora-shared-consul.svc.cluster.local:8500
  SPARK_ORIGINATION_CONSUL_SERVICE_NAME: sta-1-origination-api
  SPARK_ORIGINATION_CONSUL_SERVICE_ADDRESS: origination-api.lendora-sta-1.svc.cluster.local
  SPARK_ORIGINATION_CONSUL_HTTP_PORT: "80"
  SPARK_ORIGINATION_CONSUL_HEALTH_CHECK_URL: http://origination-api.lendora-sta-1.svc.cluster.local:80/ready
  SPRING_CLOUD_CONSUL_ENABLED: "true"
  SPRING_CLOUD_CONSUL_HOST: consul.lendora-shared-consul.svc.cluster.local
  SPRING_CLOUD_CONSUL_PORT: "8500"
  SPRING_CLOUD_CONSUL_CONFIG_ENABLED: "true"
  SPRING_CLOUD_CONSUL_CONFIG_PREFIX: spark/lendora/sta-1
  OTEL_TRACES_EXPORTER: otlp
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=sta-1
