apiVersion: v1
kind: ConfigMap
metadata:
  name: fides-bff-config
  labels:
    app.kubernetes.io/name: fides-bff
    app.kubernetes.io/part-of: lendora
data:
  config.yaml: |
    server:
      http:
        network: tcp
        addr: 0.0.0.0:8000
      cors:
        allowed_origins:
          - https://api.fuzzytails.fun
    applicant:
      consul:
        address: consul.lendora-sta-consul.svc.cluster.local:8500
        scheme: http
        service_name: applicant-api
      grpc:
        timeout: 3s
        plaintext: true
    registry:
      consul:
        enabled: true
        address: consul.lendora-sta-consul.svc.cluster.local:8500
        scheme: http
        discovery_addr: fides-bff.lendora-sta-fides-bff.svc.cluster.local:8000
        heartbeat: true
        health_check: true
        health_check_interval_sec: 10
        deregister_after_sec: 60
        metadata:
          module: frontend
          environment: sta
    observability:
      otel:
        enabled: false
        exporter: otlp
        endpoint: ""
        protocol: http/protobuf
        headers: {}
        environment: sta
        release: runtime
