apiVersion: v1
kind: Service
metadata:
  name: fides-bff
  labels:
    app.kubernetes.io/name: fides-bff
    app.kubernetes.io/part-of: lendora
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fides-bff
  ports:
    - name: http
      port: 8000
      targetPort: http
