apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: caddy
data:
  Caddyfile: |
    dog.ailuric.com {
        reverse_proxy https://cat.ailuric.com {
            header_up Host cat.ailuric.com
        }
    }

    github.fuzzytails.fun {
        reverse_proxy github-eventsource-svc.argo-events.svc.cluster.local:12000
    }

    api.fuzzytails.fun {
        handle /harness-repo {
            reverse_proxy github-eventsource-svc.argo-events.svc.cluster.local:12001
        }
        handle /business-repo {
            reverse_proxy github-eventsource-svc.argo-events.svc.cluster.local:12002
        }
        handle /idl-repo {
            reverse_proxy github-eventsource-svc.argo-events.svc.cluster.local:12003
        }
    }
