apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: caddy
data:
  Caddyfile: |
    dog.ailuric.com {
        reverse_proxy https://cat.ailuric.com {
            header_up Host cat.ailuric.com
        }
    }

    github.fuzzytails.fun {
        handle /gitops-repo {
            reverse_proxy github-eventsource-svc.argo-events.svc.cluster.local:12000
        }
        handle /harness-repo {
            reverse_proxy github-eventsource-svc.argo-events.svc.cluster.local:12001
        }
        handle /business-repo {
            reverse_proxy github-eventsource-svc.argo-events.svc.cluster.local:12002
        }
        handle /idl-repo {
            reverse_proxy github-eventsource-svc.argo-events.svc.cluster.local:12003
        }
    }

    dev-1-api.fuzzytails.fun {
        reverse_proxy fides-bff.lendora-dev-1.svc.cluster.local:8000
    }

    dev-1-fides.fuzzytails.fun {
        reverse_proxy fides.lendora-dev-1.svc.cluster.local:3000
    }

    sta-1-api.fuzzytails.fun {
        reverse_proxy fides-bff.lendora-sta-1.svc.cluster.local:8000
    }

    sta-1-fides.fuzzytails.fun {
        reverse_proxy fides.lendora-sta-1.svc.cluster.local:3000
    }
