apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-sta-quote-api
resources:
- ../../base
images:
- name: ghcr.io/spark-harness/quote-api
  digest: sha256:52373dfe19fdee70bb3ef081b7c64b280804e5e6cc6de962b0d380f71e2b1915
replicas:
- name: quote-api
  count: 1
labels:
- pairs:
    lendora.io/environment: sta
