apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-sta-fides-bff
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/fides-bff
    digest: sha256:4c13dcc0c3d23d88e0e32c1c4eaa9c6e957bdfd81e47dc42b23d8ff2717c27e1
replicas:
  - name: fides-bff
    count: 1
labels:
  - pairs:
      lendora.io/environment: sta
