apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-sta-fides-bff
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/fides-bff
    digest: sha256:e511dfff7ced08528b42dee402097c74189e1bb102daa28a73475f2115a884bb
replicas:
  - name: fides-bff
    count: 1
labels:
  - pairs:
      lendora.io/environment: sta
