apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: spark-sta1
  namespace: argocd
spec:
  description: Spark STA1 environment.
  sourceRepos:
    - https://github.com/spark-harness/gitops-repo.git
  destinations:
    - namespace: spark-sta1
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
