apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spark-sta1
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/applicant-api
    newTag: sta1-placeholder
replicas:
  - name: applicant-api
    count: 1
labels:
  - pairs:
      spark.io/environment: sta1
