apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/postgres.yaml
  - namespaces/redis.yaml
  - namespaces/consul.yaml
  - argocd-project.yaml
  - cluster.yaml
  - argocd-apps/dependencies.yaml
