apiVersion: v1
kind: ConfigMap
metadata:
  name: lendora-dev-1-cluster
  namespace: argocd
  labels:
    app.kubernetes.io/name: lendora-dev-1
    app.kubernetes.io/part-of: lendora
data:
  environment: dev-1
  namespace: lendora-dev-1
  runtimeOwner: LEN-136
