apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/business.yaml
  - argocd-project.yaml
  - cluster.yaml
  - argocd-apps/applicant-api.yaml
  - argocd-apps/quote-api.yaml
  - argocd-apps/origination-api.yaml
  - argocd-apps/fides-bff.yaml
  - argocd-apps/fides.yaml
