apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lendora-sta-1-origination-api
  namespace: argocd
spec:
  project: lendora-sta-1
  source:
    repoURL: https://github.com/spark-harness/gitops-repo.git
    targetRevision: master
    path: apps/origination-api/overlays/sta-1
  destination:
    server: https://kubernetes.default.svc
    namespace: lendora-sta-1
