apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - namespaces.yaml
  - argocd-project.yaml
  - argocd-apps/dependencies.yaml
  - argocd-apps/applicant-api.yaml
  - argocd-apps/fides-bff.yaml
  - argocd-apps/fides.yaml
