apiVersion: v1
kind: ConfigMap
metadata:
  name: quote-api-config
  labels:
    app.kubernetes.io/name: quote-api
    app.kubernetes.io/part-of: lendora
data:
  SPRING_PROFILES_ACTIVE: sta-1
  SERVER_PORT: "8080"
  QUOTE_JDBC_URL: jdbc:postgresql://postgres.lendora-shared-postgres.svc.cluster.local:5432/sta_1_quote
  QUOTE_JDBC_USERNAME: sta_1_quote
  SPARK_QUOTE_CONSUL_ENABLED: "true"
  SPARK_QUOTE_CONSUL_URL: http://consul.lendora-shared-consul.svc.cluster.local:8500
  SPARK_QUOTE_CONSUL_SERVICE_NAME: sta-1-quote-api
  SPARK_QUOTE_CONSUL_SERVICE_ADDRESS: quote-api.lendora-sta-1.svc.cluster.local
  SPARK_QUOTE_CONSUL_HTTP_PORT: "80"
  SPARK_QUOTE_CONSUL_HEALTH_CHECK_URL: http://quote-api.lendora-sta-1.svc.cluster.local:80/ready
  SPRING_CLOUD_CONSUL_ENABLED: "true"
  SPRING_CLOUD_CONSUL_HOST: consul.lendora-shared-consul.svc.cluster.local
  SPRING_CLOUD_CONSUL_PORT: "8500"
  SPRING_CLOUD_CONSUL_CONFIG_ENABLED: "true"
  SPRING_CLOUD_CONSUL_CONFIG_PREFIX: spark/lendora/sta-1
  OTEL_TRACES_EXPORTER: otlp
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=sta-1
