apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
  labels:
    app.kubernetes.io/name: quote-api
    app.kubernetes.io/part-of: lendora
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quote-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quote-api
        app.kubernetes.io/part-of: lendora
    spec:
      serviceAccountName: quote-api
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: quote-api
          image: ghcr.io/spark-harness/quote-api:replace-me
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: quote-api-config
          env:
            - name: QUOTE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quote-api-runtime
                  key: db-password
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
