apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      lendora.io/environment: sta
patches:
  - target:
      kind: Deployment
      name: postgres
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: lendora-sta-postgres
  - target:
      kind: Service
      name: postgres
    patch: |-
      - op: add
        path: /metadata/namespace
        value: lendora-sta-postgres
  - target:
      kind: Job
      name: quote-postgres-init
    patch: |-
      - op: add
        path: /metadata/namespace
        value: lendora-sta-postgres
  - target:
      kind: Job
      name: origination-postgres-init
    patch: |-
      - op: add
        path: /metadata/namespace
        value: lendora-sta-postgres
  - target:
      kind: Deployment
      name: redis
    patch: |-
      - op: add
        path: /metadata/namespace
        value: lendora-sta-redis
  - target:
      kind: Service
      name: redis
    patch: |-
      - op: add
        path: /metadata/namespace
        value: lendora-sta-redis
  - target:
      kind: Deployment
      name: consul
    patch: |-
      - op: add
        path: /metadata/namespace
        value: lendora-sta-consul
  - target:
      kind: Service
      name: consul
    patch: |-
      - op: add
        path: /metadata/namespace
        value: lendora-sta-consul
