apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-dev-1
resources:
- ../../base
images:
- name: ghcr.io/spark-harness/quote-api
  digest: sha256:caa13ee0036295c3b23121830eb6aa0d590e9f8c7821de6a2c0092bb83f2385d
replicas:
- name: quote-api
  count: 1
labels:
- pairs:
    lendora.io/environment: dev-1
patches:
- target:
    kind: ConfigMap
    name: quote-api-config
  patch: "- op: replace\n  path: /data/SPRING_PROFILES_ACTIVE\n  value: dev-1\n- op:\
    \ replace\n  path: /data/QUOTE_JDBC_URL\n  value: jdbc:postgresql://postgres.lendora-shared-postgres.svc.cluster.local:5432/dev_1_quote\n\
    - op: replace\n  path: /data/QUOTE_JDBC_USERNAME\n  value: dev_1_quote\n- op:\
    \ replace\n  path: /data/SPARK_QUOTE_CONSUL_URL\n  value: http://consul.lendora-shared-consul.svc.cluster.local:8500\n\
    - op: replace\n  path: /data/SPARK_QUOTE_CONSUL_SERVICE_NAME\n  value: dev-1-quote-api\n\
    - op: replace\n  path: /data/SPARK_QUOTE_CONSUL_SERVICE_ADDRESS\n  value: quote-api.lendora-dev-1.svc.cluster.local\n\
    - op: replace\n  path: /data/SPARK_QUOTE_CONSUL_HEALTH_CHECK_URL\n  value: http://quote-api.lendora-dev-1.svc.cluster.local:80/ready"
- target:
    kind: ConfigMap
    name: quote-api-consul-config
  patch: "- op: replace\n  path: /data/quote-api.yml\n  value: |\n    spark:\n   \
    \   quote:\n        validity: 30m\n        consul:\n          enabled: true\n\
    \          service-name: dev-1-quote-api\n          service-address: quote-api.lendora-dev-1.svc.cluster.local\n\
    \          http-port: 80\n          health-check-url: http://quote-api.lendora-dev-1.svc.cluster.local:80/ready\n\
    \    otel:\n      service:\n        name: quote-api\n      traces:\n        exporter:\
    \ otlp\n        sampler: parentbased_traceidratio\n        sampler.arg: 0.1\n\
    \      exporter:\n        otlp:\n          traces:\n            protocol: http/protobuf"
- target:
    kind: Job
    name: quote-api-consul-config
  patch: "- op: replace\n  path: /spec/template/spec/containers/0/command/2\n  value:\
    \ |\n    curl --fail --request PUT --data-binary @/config/quote-api.yml \\\n \
    \     http://consul.lendora-shared-consul.svc.cluster.local:8500/v1/kv/spark/lendora/dev-1/quote-api/config"
- target:
    kind: NetworkPolicy
    name: quote-api-ingress
  patch: "- op: replace\n  path: /spec/ingress\n  value:\n    - from:\n        - namespaceSelector:\n\
    \            matchLabels:\n              kubernetes.io/metadata.name: lendora-dev-1\n\
    \      ports:\n        - protocol: TCP\n          port: 8080\n        - protocol:\
    \ TCP\n          port: 80\n    - from:\n        - namespaceSelector:\n       \
    \     matchLabels:\n              kubernetes.io/metadata.name: lendora-shared-consul\n\
    \      ports:\n        - protocol: TCP\n          port: 8080"
