apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-sta-applicant-api
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/applicant-api
    digest: sha256:769a1a1c67b554d061f460936e19c7beb9caaecd2b474e839a30d1b25eb39178
replicas:
  - name: applicant-api
    count: 1
labels:
  - pairs:
      lendora.io/environment: sta
