apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lendora-sta-applicant-api
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/applicant-api
    digest: sha256:70b3a3f5c0179b11a8171e7bbdb254020f29e6c1471a93a70827776c50504ff3
replicas:
  - name: applicant-api
    count: 1
labels:
  - pairs:
      lendora.io/environment: sta
