apiVersion: v1
kind: Service
metadata:
  name: fides
  labels:
    app.kubernetes.io/name: fides
    app.kubernetes.io/part-of: lendora
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fides
  ports:
    - name: http
      port: 3000
      targetPort: http
