apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spark-sta2
resources:
  - ../../base
images:
  - name: ghcr.io/spark-harness/applicant-api
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
replicas:
  - name: applicant-api
    count: 1
labels:
  - pairs:
      spark.io/environment: sta2
