apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-argocd-sta1
  namespace: argocd
spec:
  project: spark-sta1
  source:
    repoURL: https://github.com/spark-harness/gitops-repo.git
    targetRevision: master
    path: platform/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
